let vacancies = [
    {   
        idCreator: 100,
        id:1,
        companyName: "Banco Inter",
        vacancyName: "Senior Software Enginner",
        status: "In process",
        type: "Pleno",
        time: "Full Time",
        payment: "1700",
        uf: "SP",
        requirements: [
            "JavaScript",
            "Html",
            "Css",
            "Bootstrap",
            "ReactJs",
            "Vue",
            "Angular",
            "MySQL"
        ],
        desirable: [
            "PowerPoint",
            "PacoteOfficie",
            "MovieMaker",
            "Ilustrator",
            "Photoshop",
            "CorelDraw",
            "Lumia Fusion",
            "Word",
        ],
        benefits: [
            "Vale Transoporte",
            "Vale Refeição",
            "100% Home Offcie",
            "Comissao por vendas",
            "Cargo Escalavel"
        ],
        additional: "Temos reuniões todas as sextas feiras as 19hrs, é desejavel que todos os intengrantes da equipe participem",
        date: {
            year: 2019,
            month: 2,
            day: 3,
        },
    },

    {   
        idCreator: 100,
        id:2,
        companyName: "Banco Inter",
        vacancyName: "Systems Analysis",
        status: "In process",
        type: "Junior",
        time: "Night Time",
        payment: "800",
        uf: "SP",
        requirements: [
            "Inter Example 1",
            "Inter Example 2",
            "Inter Example 3",
            "Inter Example 4",
            "Inter Example 5",
        ],
        desirable: [
            "Inter Example 6",
            "Inter Example 7",
            "Inter Example 8",
            "Inter Example 9",
            "Inter Example 10",
        ],
        benefits: [
            "Inter Example 11",
            "Inter Example 12",
            "Inter Example 13",
            "Inter Example 14",
            "Inter Example 15",
        ],
        additional: "Example of additional job information",
        date: {
            year: 2022,
            month: 2,
            day: 3,
        },
    },

    {   
        idCreator: 100,
        id:3,
        companyName: "Banco Inter",
        vacancyName: "Production assistant",
        status: "In process",
        type: "Trainee",
        time: "Full Time",
        payment: "4500",
        uf: "SP",
        requirements: [
            "Example 1",
            "Example 2",
            "Example 3",
            "Example 4",
            "Example 5",
        ],
        desirable: [
            "Example 6",
            "Example 7",
            "Example 8",
            "Example 9",
            "Example 10",
        ],
        benefits: [
            "Example 11",
            "Example 12",
            "Example 13",
            "Example 14",
            "Example 15",
        ],
        additional: "Some example of information",
        date: {
            year: 2021,
            month: 10,
            day: 24,
        },
    },

    {   
        idCreator: 100,
        id:4,
        companyName: "Banco Inter",
        vacancyName: "Systems Analysis",
        status: "In process",
        type: "Senior",
        time: "Part time",
        payment: "7500",
        uf: "SP",
        requirements: [
            "More Example 1",
            "More Example 2",
            "More Example 3",
            "More Example 4",
            "More Example 5",
        ],
        desirable: [
            "More Example 6",
            "More Example 7",
            "More Example 8",
            "More Example 9",
            "More Example 10",
        ],
        benefits: [
            "More Example 11",
            "More Example 12",
            "More Example 13",
            "More Example 14",
            "More Example 15",
        ],
        additional: "No additional information",
        date: {
            year: 2022,
            month: 2,
            day: 4,
        },
    },

    {   
        idCreator: 101,
        id: 5,
        companyName: "PicPay",
        vacancyName: "Security Expert",
        status: "In process",
        type: "Pleno",
        time: "Part time",
        payment: "5200",
        uf: "RJ",
        requirements: [
            "Item 1",
            "Item 2",
            "Item 3",
            "Item 4",
            "Item 5",
        ],
        desirable: [
            "Item 6",
            "Item 7",
            "Item 8",
            "Item 9",
            "Item 10",
        ],
        benefits: [
            "Item 11",
            "Item 12",
            "Item 13",
            "Item 14",
            "Item 15",
        ],
        additional: "Item with additional information",
        date: {
            year: 2021,
            month: 2,
            day: 4,
        },
    },

    {   
        idCreator: 101,
        id: 6,
        companyName: "PicPay",
        vacancyName: "Data Analyst",
        status: "In process",
        type: "Junior",
        time: "Full Time",
        payment: "1200",
        uf: "RJ",
        requirements: [
            "Item Example 1",
            "Item Example 2",
            "Item Example 3",
            "Item Example 4",
            "Item Example 5",
        ],
        desirable: [
            "Item Example 6",
            "Item Example 7",
            "Item Example 8",
            "Item Example 9",
            "Item Example 10",
        ],
        benefits: [
            "Item Example 11",
            "Item Example 12",
            "Item Example 13",
            "Item Example 14",
            "Item Example 15",
        ],
        additional: "No additional information",
        date: {
            year: 2022,
            month: 1,
            day: 4,
        },
    },

    {   
        idCreator: 101,
        id: 7,
        companyName: "PicPay",
        vacancyName: "Designer de front-end",
        status: "In process",
        type: "Senior",
        time: "PJ",
        payment: "4100",
        uf: "RJ",
        requirements: [
            "List item 1",
            "List item 2",
            "List item 3",
            "List item 4",
            "List item 5",
        ],
        desirable: [
            "List item 6",
            "List item 7",
            "List item 8",
            "List item 9",
            "List item 10",
        ],
        benefits: [
            "List item 11",
            "List item 12",
            "List item 13",
            "List item 14",
            "List item 15",
        ],
        additional: "More info",
        date: {
            year: 2018,
            month: 1,
            day: 4,
        },
    },

    {   
        idCreator: 101,
        id: 8,
        companyName: "PicPay",
        vacancyName: "Programmer backend",
        status: "In process",
        type: "Trainee",
        time: "Part time",
        payment: "700",
        uf: "RJ",
        requirements: [
            "Topic 1",
            "Topic 2",
            "Topic 3",
            "Topic 4",
            "Topic 5",
        ],
        desirable: [
            "Topic 6",
            "Topic 7",
            "Topic 8",
            "Topic 9",
            "Topic 10",
        ],
        benefits: [
            "Topic 11",
            "Topic 12",
            "Topic 13",
            "Topic 14",
            "Topic 15",
        ],
        additional: "Topic example ",
        date: {
            year: 2021,
            month: 5,
            day: 4,
        },
    },

    {   
        idCreator: 102,
        id: 9,
        companyName: "Nubank",
        vacancyName: "Programmer full stack",
        status: "In process",
        type: "Pleno",
        time: "Full Time",
        payment: "7500",
        uf: "MG",
        requirements: [
            "Test 1",
            "Test 2",
            "Test 3",
            "Testc 4",
            "Test 5",
        ],
        desirable: [
            "Test 6",
            "Test 7",
            "Test 8",
            "Test 9",
            "Test 10",
        ],
        benefits: [
            "Test 11",
            "Test 12",
            "Test 13",
            "Test 14",
            "Test 15",
        ],
        additional: "Test example ",
        date: {
            year: 2010,
            month: 5,
            day: 4,
        },
    },

    {   
        idCreator: 102,
        id: 10,
        companyName: "Nubank",
        vacancyName: "Data engineer",
        status: "In process",
        type: "Pleno",
        time: "Part time",
        payment: "2200",
        uf: "MG",
        requirements: [
            "Item 1",
            "Item 2",
            "Item 3",
            "Item 4",
            "Item 5",
        ],
        desirable: [
            "Item 6",
            "Item 7",
            "Item 8",
            "Item 9",
            "Item 10",
        ],
        benefits: [
            "Item 11",
            "Item 12",
            "Item 13",
            "Item 14",
            "Item 15",
        ],
        additional: "Item with additional information",
        date: {
            year: 2020,
            month: 2,
            day: 4,
        },
    },

    {   
        idCreator: 103,
        id: 11,
        companyName: "Apple",
        vacancyName: "IOS Developoer",
        status: "In process",
        type: "Junior",
        time: "Full Time",
        payment: "5200",
        uf: "GO",
        requirements: [
            "List item 1",
            "List item 2",
            "List item 3",
            "List item 4",
            "List item 5",
        ],
        desirable: [
            "List item 6",
            "List item 7",
            "List item 8",
            "List item 9",
            "List item 10",
        ],
        benefits: [
            "List item 11",
            "List item 12",
            "List item 13",
            "List item 14",
            "List item 15",
        ],
        additional: "Item with additional information",
        date: {
            year: 2021,
            month: 5,
            day: 4,
        },
    },

    {   
        idCreator: 103,
        id: 12,
        companyName: "Apple",
        vacancyName: "Production Assistant",
        status: "In process",
        type: "Junior",
        time: "Full Time",
        payment: "5200",
        uf: "GO",
        requirements: [
            "More Example 1",
            "More Example 2",
            "More Example 3",
            "More Example 4",
            "More Example 5",
        ],
        desirable: [
            "More Example 6",
            "More Example 7",
            "More Example 8",
            "More Example 9",
            "More Example 10",
        ],
        benefits: [
            "More Example 11",
            "More Example 12",
            "More Example 13",
            "More Example 14",
            "More Example 15",
        ],
        additional: "Item with additional information",
        date: {
            year: 2021,
            month: 5,
            day: 4,
        },
    },

    {   
        idCreator: 103,
        id: 13,
        companyName: "Apple",
        vacancyName: "Production Engineer",
        status: "In process",
        type: "Senior",
        time: "Moorning time",
        payment: "8500",
        uf: "GO",
        requirements: [
            "Test 1",
            "Test 2",
            "Test 3",
            "Testc 4",
            "Test 5",
        ],
        desirable: [
            "Test 6",
            "Test 7",
            "Test 8",
            "Test 9",
            "Test 10",
        ],
        benefits: [
            "Test 11",
            "Test 12",
            "Test 13",
            "Test 14",
            "Test 15",
        ],
        additional: "Additional information",
        date: {
            year: 2022,
            month: 4,
            day: 3,
        },
    },
]